name: Workflow1

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  workflow1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Workflow1
        run: echo "Hello Workflow1!"
