name: Workflow2

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  dump-contexts:
    uses: ./.github/workflows/dump-contexts.yml
    secrets: inherit

  pre-workflow2:
    uses: ./.github/workflows/workflow1.yml
    secrets: inherit

  workflow2:
    needs: pre-workflow2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0 # load the entire history, otherwise git will not find the branch

      - name: Workflow2
        run: echo "Hello Workflow2!"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Find branch for tag
        run: |
          BRANCHES=$(git branch -r --contains ${{ github.sha }} | grep -v HEAD | sed 's/origin\///')
          DEFAULT=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          for BRANCH in $BRANCHES; do
            if [[ "$BRANCH" != "$DEFAULT" && "$BRANCH" != "main" ]]; then
              echo "BRANCH=$BRANCH" >> $GITHUB_ENV
              exit 0
            fi
          done
          echo "BRANCH=$DEFAULT" >> $GITHUB_ENV

      - name: Print branch
        run: echo "Tag was created from branch $BRANCH"

      - name: Check if tag is on main branch
        run: |
          branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "Branch is $branch."
          if [ "$branch" != "main" ]; then
            echo "Error: Tag must be on main branch!"
            exit 1
          fi
