name: Workflow2

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  dump-contexts:
    uses: ./.github/workflows/dump-contexts.yml
    secrets: inherit

  pre-workflow2:
    uses: ./.github/workflows/workflow1.yml
    secrets: inherit

  workflow2:
    needs: pre-workflow2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # load the entire history, otherwise git will not find the branch

      - name: Check if tag is on main branch
        run: |
          branches=$(git branch -r --contains ${{ github.sha }} | grep -v HEAD | sed 's/origin\///')
          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          for branch in $branches; do
            if [[ "$branch" != "$default_branch" && "$branch" != "main" ]]; then
              echo "Error: Tag must be on main branch!"
              exit 1
            fi
          done

      - name: Workflow2
        run: echo "Hello Workflow2!"
